/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Terrain.glb 
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

const Terrain = (props) => {
  const { nodes, materials } = useGLTF("./models/Terrain.glb");

  const terrainTexture = useTexture("./textures/TT/TT_Terrain02.jpg");
  terrainTexture.flipY = false;

  // VERY IMPORTANT ↓
  terrainTexture.colorSpace = THREE.SRGBColorSpace;

  const terrainFloor = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: terrainTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [terrainTexture]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_1.geometry}
        // material={materials['Sketch_maps_Limpia.001']}
        material={terrainFloor}
      />
    </group>
  );
};

useGLTF.preload("./models/Terrain.glb");

export default Terrain;
